#!/usr/bin/env bash

SR_ENDPOINT="http://semantic-representation:5000"

while ! $(curl -I $SR_ENDPOINT > /dev/null 2>&1); do
    echo "SR not yet ready at $SR_ENDPOINT"
    sleep 1
done
echo "SR ready at $SR_ENDPOINT !"

/scripts/dockerize -wait tcp://kafka-marketplace-broker:19092 -timeout 15s

./start_backend